name: "Splight Push Component"
description: "Automatically find updated components and push them to Splight Hub."
author: "Marco Martinelli"
inputs:
  splight_access_id:
    description: "Splight Hub access key id."
    required: false # TODO: a true
  splight_secret_key:
    description: "Splight Hub private key."
    required: false # TODO: a true
  splight_platform_api_host:
    description: "Splight platform API endpoint."
    required: false
  spec_file:
    description: "Path to the component's configuration file ("spec.json")."
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.splight_access_id }}
    - ${{ inputs.splight_secret_key }}
    - ${{ inputs.splight_platform_api_host }}
    - ${{ inputs.spec_file }}